name: Auto Sports Scraper

on:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিট পর পর অটো রান হবে
  workflow_dispatch: # চাইলে আপনি নিজেও ম্যানুয়ালি ক্লিক করে রান করতে পারবেন

permissions:
  contents: write # গিটহাবে ফাইল পুশ করার পারমিশন

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/actions-setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper Script
      env:
        MY_AES_KEY: ${{ secrets.MY_AES_KEY }}
        MY_AES_IV: ${{ secrets.MY_AES_IV }}
        MY_BASE_URL: ${{ secrets.MY_BASE_URL }}
      run: python test.py

    - name: Commit and Push Clean JSON File
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add decrypted_events.json
        git diff-index --quiet HEAD || git commit -m "🤖 Auto-updated Live Match Data [Skip CI]"
        git push
