name: Auto Sports Scraper to Hosting

on:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিট পর পর রান হবে
  workflow_dispatch: # ম্যানুয়াল রান অপশন

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper Script
      env:
        MY_AES_KEY: ${{ secrets.MY_AES_KEY }}
        MY_AES_IV: ${{ secrets.MY_AES_IV }}
        MY_BASE_URL: ${{ secrets.MY_BASE_URL }}
        MY_RECEIVER_URL: ${{ secrets.MY_RECEIVER_URL }}
        MY_HOSTING_TOKEN: ${{ secrets.MY_HOSTING_TOKEN }}
      run: python test.py
